server:
  port: 8210

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: nishi213
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  # 配置 Redis
  redis:
    host: 47.115.148.227
    password: nishi213
    timeout: 5000
    database: 0

# fastdep-shiro-jwt 配置
fastdep:
  shiro-jwt:
    filter:
      # 不拦截
      front:
        path: /auth/login
        role: anon
      # 拦截
      logout:
        path: /auth/logout
        role: jwt
      admin:
        path: /admin/**
        role: jwt
      users:
        path: /users/**
        role: jwt
      books:
        path: /books/**
        role: jwt
    secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52
    # token 有效期
    expireTime: 7200000
    # token 校验时的前缀
    prefix: ""
    # token 生成签名的前缀
    signPrefix: ""
    # token 校验时的 header 头
    header: "Authorization"

# 日志配置
logging:
  level:
    com.cgh.library.persistence.repository: DEBUG

# 启动 Swagger
swagger:
  enabled=true: