server:
  port: 8210

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: nishi213
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  # 配置 Redis
  redis:
    host: 127.0.0.1
    password:
    timeout: 5000
    database: 0
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.163.com
    userename: cghAkuma@163.com
    password:
    properties.mail.smtp.port: 456
    from: cghAkuma@163.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


#  spring.jackson.default-property-inclusion=non_null
#  spring.jackson.time-zone=GMT+8
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.open-in-view=true
#  spring.jpa.show-sql=true

# fastdep-shiro-jwt 配置
fastdep:
  shiro-jwt:
    filter:
      # 不拦截
      front:
        path: /auth/login
        role: anon
      reigster:
        path: /auth/register
        role: anon
      # 拦截
      logout:
        path: /auth/logout
        role: jwt
      admin:
        path: /admin/**
        role: jwt
      users:
        path: /users/**
        role: jwt
      books:
        path: /books/**
        role: jwt
      tieba:
        path: /tieba/**
        role: jwt
    secret: 6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52
    # token 有效期
    expireTime: 7200000
    # token 校验时的前缀
    prefix: ""
    # token 生成签名的前缀
    signPrefix: ""
    # token 校验时的 header 头
    header: "Authorization"

# 日志配置
logging:
  level:
    com.cgh.library.persistence.repository: DEBUG

# 启动 Swagger
swagger:
  enabled=true: